# Generated by Django 4.0.5 on 2022-09-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationUseModel',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
