# Generated by Django 4.0.5 on 2022-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('companyEmail', models.CharField(max_length=50)),
                ('companyAddress', models.CharField(max_length=255)),
                ('companyTele', models.CharField(max_length=255)),
                ('companyResume', models.CharField(max_length=400)),
                ('salt', models.CharField(max_length=10)),
                ('hash', models.CharField(db_column='HASH', max_length=32)),
            ],
            options={
                'db_table': 'Companys',
                'managed': True,
            },
        ),
    ]
